### ISSUE TITLE
cli release

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/pib-cli#599]
- because pib-cli is private, you can't get to the releases to install the CLI without a PAT
- we will need some way to publish the CLI (likely to pib-dev)
- we will need to update ci-cd to automatically create the releases
~~we will need to update ci-cd to automatically create the beta-release~~

DoD
- [ ] pib-cli is a private repo that contains the source code
- [x] pib-dev is a public repo
- [x] pib dev contains release packages for the 3 CLIs
  - [x] source code is not in the packages (links are to pib-dev
- [ ] the CLIs can be installed via "wget" and "tar" without authentication
- [x] there is a ci-cd process that automatically creates the packages when a GitHub Release is created
- [x] linux x86 only

**Comment by bartr** [comment]
"a" way to do this

on the public repo
- create a release action
- clone the cli repo
- checkout the tag
- build and publish the release
- the only differences with the current implementation is cloning the repo, checking out the tag, and not building beta-release
- you will need a PAT that can read the CLI repo

For the beta-release
- create an Action on cli repo that dispatches to an action on the public repo
- on the public repo
- create an action
- clone the CLI repo
- build and publish the beta-release
- use the same token for both Actions

That is "a" way. It seems reasonable from a complexity perspective but there may be better approaches.

**Comment by DanMass** [comment]
@bartr, do you have a DoD version of the above?  _We should be in the habit of defining DoD based on end state, not potential ways to accomplish the task._

Is the desired end state that the pib-cli release version and assets are also published to pib-dev. For example the 0.8.3 release and its assets would exist in both pib-cli and pib-dev? And that they would be identical? If we had a way, for example, to just copy the release and assets from pib-cli to pib-dev, does that satisfy DoD?

I have the same question for beta-release, although it seems like beta-release is an overwrite. Is there a reason we don't have a version for beta-release in pib-cli? If I look at the release or the asset files, I should know which release it's a beta for, etc.

Actually, I would expect us to just tag a certain release# as the beta, instead of this version-less beta we have now.

**Comment by bartr** [comment]
- since beta-release is internal only, we agreed to remove from scope
- added DoD

There is no requirement in DoD for the packages to exist on pib-cli. It's OK, perhaps valuable, if they do.

**Comment by DanMass** [comment]
@bartr, may I please have an action secret in pib-cli with a token that can write to pib-dev. I'd prefer to push from the repo/action that already builds the release than to have two copies of the release action to maintain in the two repos. I think it's also cleaner to build the code where we do the work and publish via push.

**Comment by DanMass** [comment]
Hs1r1us/Release-AIO@v1.0 does what we expected. It copies the release from the current repo to the other repo. I tested with a fork of pib-cli and a new repo.

**Comment by DanMass** [comment]
We've (right) closed this _and_ we should tick off that last check box in the DoD when we make pib-cli private.
